const defaultRequirements = [
  {
    title: 'Financial Management Act 1994 reporting control mapping',
    source: 'Financial Management Act 1994 (Vic)',
    category: 'Legislation',
    obligationType: 'statutory_reporting',
    status: 'in_progress',
    dueDate: '2026-08-10',
    owner: 'Finance Controller',
    reportType: 'Financial statements',
    materiality: 'High',
    approvalRequired: true,
    evidenceRequired: ['Budget variance report', 'Board sign-off', 'Ledger extract'],
    details: 'Map statutory obligations to reporting controls and evidence requirements.',
  },
  {
    title: 'Treasurer\'s Directions compliance review',
    source: 'Treasurer\'s Directions',
    category: 'Policy',
    obligationType: 'compliance_review',
    status: 'completed',
    dueDate: '2026-07-20',
    owner: 'Compliance Lead',
    reportType: 'Compliance review',
    materiality: 'Medium',
    approvalRequired: false,
    evidenceRequired: ['Policy checklist', 'Signed attestation'],
    details: 'Validate standing directions obligations against current reporting workflows.',
  },
  {
    title: 'AASB/IFRS disclosure evidence pack',
    source: 'AASB / IFRS',
    category: 'Accounting standard',
    obligationType: 'disclosure_pack',
    status: 'blocked',
    dueDate: '2026-09-15',
    owner: 'Accounting Lead',
    reportType: 'Audit evidence',
    materiality: 'High',
    approvalRequired: true,
    evidenceRequired: ['Disclosure memo', 'Trial balance export', 'Audit support note'],
    details: 'Prepare evidence for statutory disclosure review and audit challenge points.',
  },
];

module.exports = defaultRequirements;
