/**
 * Default IRIS reporting obligations seeded on first workspace load.
 * Based on: Financial Management Act 1994 (Vic), Standing Directions 2018,
 * Treasurer's Directions, AASB/IFRS, GDPR, and Department policies.
 */
const defaultRequirements = [
  // ── Financial Management Act 1994 ────────────────────────────────────────
  {
    title: "Annual Financial Statements preparation and submission",
    source: "Financial Management Act 1994 (Vic)",
    legislationRef: "FMA s.51",
    category: "Legislation",
    obligationType: "statutory_reporting",
    status: "in_progress",
    dueDate: "2026-10-31",
    owner: "Chief Finance Officer",
    reportType: "Financial statements",
    materiality: "Critical",
    approvalRequired: true,
    reportingPeriod: "FY2025-26",
    legislationVersion: "FMA 1994 — 2018 Amendment",
    ruleVersion: "2.1",
    evidenceRequired: [
      "Signed financial statements",
      "Independent auditor report",
      "Secretary certification letter",
      "Board resolution approving statements",
      "Budget variance analysis",
    ],
    details: "Prepare, have audited, and submit annual financial statements to the Minister and Auditor-General within the prescribed timeframe under s.51 FMA 1994.",
    approvalSteps: [
      { stepName: "CFO Review", assignedTo: "Chief Finance Officer", order: 1, status: "pending" },
      { stepName: "Audit Committee Sign-off", assignedTo: "Audit Committee Chair", order: 2, status: "pending" },
      { stepName: "Secretary Certification", assignedTo: "Department Secretary", order: 3, status: "pending" },
    ],
  },

  // ── Standing Directions 2018 ────────────────────────────────────────────
  {
    title: "Standing Direction 4.2.1 — Annual report financial disclosures",
    source: "Standing Directions 2018 (Vic)",
    legislationRef: "SD 4.2.1",
    category: "Policy",
    obligationType: "compliance_review",
    status: "planned",
    dueDate: "2026-10-31",
    owner: "Compliance Lead",
    reportType: "Annual report",
    materiality: "High",
    approvalRequired: true,
    reportingPeriod: "FY2025-26",
    legislationVersion: "Standing Directions 2018 v3",
    ruleVersion: "1.0",
    evidenceRequired: [
      "Completed SD 4.2.1 checklist",
      "Signed attestation from Secretary",
      "Evidence of internal control review",
    ],
    details: "Validate that all financial disclosures in the annual report comply with SD 4.2.1 requirements, including statement of financial position, comprehensive income, cash flows, and changes in equity.",
    approvalSteps: [
      { stepName: "Finance Manager Review", assignedTo: "Finance Manager", order: 1, status: "pending" },
      { stepName: "CFO Sign-off", assignedTo: "CFO", order: 2, status: "pending" },
    ],
  },

  {
    title: "Standing Direction 4.5.5 — Asset management attestation",
    source: "Standing Directions 2018 (Vic)",
    legislationRef: "SD 4.5.5",
    category: "Policy",
    obligationType: "compliance_review",
    status: "planned",
    dueDate: "2026-09-30",
    owner: "Asset Manager",
    reportType: "Compliance review",
    materiality: "High",
    approvalRequired: true,
    reportingPeriod: "FY2025-26",
    legislationVersion: "Standing Directions 2018 v3",
    ruleVersion: "1.0",
    evidenceRequired: [
      "Asset register extract",
      "Revaluation schedule",
      "Impairment assessment memo",
      "Physical verification sign-off",
    ],
    details: "Annual attestation that all assets are properly identified, valued, maintained and reported in accordance with SD 4.5.5 and relevant accounting standards.",
    approvalSteps: [
      { stepName: "Asset Manager Review", assignedTo: "Asset Manager", order: 1, status: "pending" },
      { stepName: "CFO Attestation", assignedTo: "CFO", order: 2, status: "pending" },
    ],
  },

  // ── Treasurer's Directions ────────────────────────────────────────────
  {
    title: "Treasurer's Directions — Banking and investment compliance",
    source: "Treasurer's Directions",
    legislationRef: "TD Part 5",
    category: "Policy",
    obligationType: "compliance_review",
    status: "completed",
    dueDate: "2026-07-31",
    owner: "Treasury Manager",
    reportType: "Compliance review",
    materiality: "Medium",
    approvalRequired: false,
    reportingPeriod: "FY2025-26",
    legislationVersion: "Treasurer's Directions 2023",
    ruleVersion: "1.2",
    evidenceRequired: [
      "Bank account register",
      "Investment policy attestation",
      "Quarterly cash flow report",
    ],
    details: "Review all banking arrangements and investments for compliance with Treasurer's Directions Part 5, including authorised investments and surplus cash management.",
  },

  // ── AASB / IFRS ────────────────────────────────────────────────────────
  {
    title: "AASB 16 — Lease accounting disclosure evidence pack",
    source: "AASB 16 / IFRS 16",
    legislationRef: "AASB 16",
    category: "Accounting standard",
    obligationType: "disclosure_pack",
    status: "in_progress",
    dueDate: "2026-09-15",
    owner: "Accounting Lead",
    reportType: "Audit evidence",
    materiality: "High",
    approvalRequired: true,
    reportingPeriod: "FY2025-26",
    legislationVersion: "AASB 16 — 2023",
    ruleVersion: "1.0",
    evidenceRequired: [
      "Lease register",
      "Right-of-use asset calculation",
      "Lease liability schedule",
      "Discount rate justification memo",
      "Auditor workpapers",
    ],
    details: "Prepare comprehensive evidence for AASB 16 lease accounting, including right-of-use asset balances, lease liabilities, discount rates applied, and associated disclosures in note form.",
    approvalSteps: [
      { stepName: "Accounting Lead Review", assignedTo: "Accounting Lead", order: 1, status: "pending" },
      { stepName: "External Auditor Clearance", assignedTo: "Audit Partner", order: 2, status: "pending" },
    ],
  },

  {
    title: "AASB 1058 — Income of not-for-profit entities disclosure",
    source: "AASB 1058",
    legislationRef: "AASB 1058",
    category: "Accounting standard",
    obligationType: "disclosure_pack",
    status: "blocked",
    dueDate: "2026-09-15",
    owner: "Accounting Lead",
    reportType: "Audit evidence",
    materiality: "High",
    approvalRequired: true,
    reportingPeriod: "FY2025-26",
    legislationVersion: "AASB 1058 — 2023",
    ruleVersion: "1.0",
    evidenceRequired: [
      "Grant revenue register",
      "Volunteer services valuation note",
      "Performance obligations assessment",
      "Revenue recognition policy memo",
    ],
    details: "Document and evidence the application of AASB 1058 for recognition of income for not-for-profit entities, including grants, donations, and volunteer services.",
  },

  // ── GDPR / Privacy ────────────────────────────────────────────────────
  {
    title: "Privacy Act / GDPR — Annual privacy compliance report",
    source: "Privacy Act 1988 (Cth) / GDPR",
    legislationRef: "Privacy Act s.15 / GDPR Art.30",
    category: "Compliance",
    obligationType: "compliance_review",
    status: "planned",
    dueDate: "2026-11-30",
    owner: "Privacy Officer",
    reportType: "Compliance review",
    materiality: "Medium",
    approvalRequired: true,
    reportingPeriod: "FY2025-26",
    legislationVersion: "Privacy Act 2024 Amendment",
    ruleVersion: "1.0",
    evidenceRequired: [
      "Data register (ROPA)",
      "Privacy impact assessment",
      "Breach notification register",
      "DPA agreements register",
      "Staff training completion records",
    ],
    details: "Annual compliance review against Privacy Act and GDPR obligations, covering data register maintenance, breach reporting, consent management, and cross-border data transfer controls.",
    approvalSteps: [
      { stepName: "Privacy Officer Review", assignedTo: "Privacy Officer", order: 1, status: "pending" },
      { stepName: "General Counsel Sign-off", assignedTo: "General Counsel", order: 2, status: "pending" },
    ],
  },

  // ── Ministerial Report ────────────────────────────────────────────────
  {
    title: "Quarterly ministerial financial performance report",
    source: "Department Policy",
    legislationRef: "Internal Policy FIN-007",
    category: "Reporting",
    obligationType: "reporting",
    status: "planned",
    dueDate: "2026-07-21",
    owner: "Finance Controller",
    reportType: "Ministerial report",
    materiality: "Standard",
    approvalRequired: true,
    reportingPeriod: "Q1 FY2025-26",
    legislationVersion: "Internal Policy FIN-007 v2",
    ruleVersion: "1.0",
    evidenceRequired: [
      "YTD budget vs actuals report",
      "Variance commentary",
      "Cash flow forecast",
      "Capital expenditure tracking",
    ],
    details: "Prepare and submit quarterly financial performance report to the Minister including budget variance analysis, forecasts, and key financial risk commentary.",
    approvalSteps: [
      { stepName: "Finance Review", assignedTo: "Finance Controller", order: 1, status: "pending" },
      { stepName: "CFO Approval", assignedTo: "CFO", order: 2, status: "pending" },
      { stepName: "Secretary Endorsement", assignedTo: "Department Secretary", order: 3, status: "pending" },
    ],
  },

  // ── Audit ─────────────────────────────────────────────────────────────
  {
    title: "Victorian Auditor-General's Office — Audit evidence pack",
    source: "Audit Act 1994 (Vic)",
    legislationRef: "Audit Act s.7A",
    category: "Legislation",
    obligationType: "audit_evidence",
    status: "planned",
    dueDate: "2026-08-31",
    owner: "Internal Audit Lead",
    reportType: "Audit evidence",
    materiality: "Critical",
    approvalRequired: true,
    reportingPeriod: "FY2025-26",
    legislationVersion: "Audit Act 1994 — current",
    ruleVersion: "1.0",
    evidenceRequired: [
      "Trial balance",
      "Journal entry testing samples",
      "Bank reconciliations",
      "Accounts payable/receivable aging",
      "Fixed asset register",
      "Accruals schedule",
      "Management representation letter",
    ],
    details: "Compile the full audit evidence pack for VAGO annual financial audit. All schedule A and B items must be provided by the nominated deadline. Late delivery triggers escalation.",
    approvalSteps: [
      { stepName: "Internal Audit Review", assignedTo: "Internal Audit Lead", order: 1, status: "pending" },
      { stepName: "CFO Clearance", assignedTo: "CFO", order: 2, status: "pending" },
    ],
  },
];

module.exports = defaultRequirements;
