const DEFAULT_TEMPLATES = [
    {
        name: 'GRC / Compliance Workflow',
        description: 'End-to-end governance, risk, and compliance process',
        category: 'Compliance',
        settings: {
            notifications: { email: true, slack: false, inApp: true },
            automation: { autoAssignTasks: false, dueDateReminders: true, escalateOverdueTasks: true },
        },
        status: 'draft',
        steps: [
            {
                title: 'Risk Identification',
                description: 'Identify and document all potential risks across the organisation',
                timeEstimate: '3d',
                notes: 'Use risk register template. Include operational, financial, and reputational risks.',
                status: 'draft',
                coordinates: { x: 100, y: 200 },
                sequence: 1,
            },
            {
                title: 'Risk Assessment',
                description: 'Evaluate likelihood and impact of each identified risk',
                timeEstimate: '2d',
                notes: 'Rate each risk on a 5x5 matrix. Prioritise high-impact items.',
                status: 'draft',
                coordinates: { x: 300, y: 200 },
                sequence: 2,
            },
            {
                title: 'Control Implementation',
                description: 'Design and apply controls to mitigate top-priority risks',
                timeEstimate: '5d',
                notes: 'Map each control to a specific risk. Document control owner.',
                status: 'draft',
                coordinates: { x: 500, y: 200 },
                sequence: 3,
            },
            {
                title: 'Monitoring & Testing',
                description: 'Test effectiveness of controls and monitor for new risks',
                timeEstimate: '4d',
                notes: 'Schedule quarterly control tests. Log all exceptions.',
                status: 'draft',
                coordinates: { x: 700, y: 200 },
                sequence: 4,
            },
            {
                title: 'Reporting to Management',
                description: 'Compile risk and compliance report for executive review',
                timeEstimate: '1d',
                notes: 'Include KRIs, control status, and open issues.',
                status: 'draft',
                coordinates: { x: 900, y: 200 },
                sequence: 5,
            },
            {
                title: 'Continuous Improvement',
                description: 'Review process outcomes and update framework based on findings',
                timeEstimate: '2d',
                notes: 'Incorporate lessons learned. Update risk register and control library.',
                status: 'draft',
                coordinates: { x: 1100, y: 200 },
                sequence: 6,
            },
        ],
    },
    {
        name: 'Legal / VCAT Workflow',
        description: 'Legal case management from client intake through VCAT enforcement',
        category: 'Legal',
        settings: {
            notifications: { email: true, slack: false, inApp: true },
            automation: { autoAssignTasks: false, dueDateReminders: true, escalateOverdueTasks: true },
        },
        status: 'draft',
        steps: [
            {
                title: 'Client Intake',
                description: 'Collect client details, matter type, and initial instructions',
                timeEstimate: '2h',
                notes: 'Complete client intake form. Verify identity and conflicts check.',
                status: 'draft',
                coordinates: { x: 100, y: 200 },
                sequence: 1,
            },
            {
                title: 'Legal Assessment',
                description: 'Assess merits of the case and advise client on options',
                timeEstimate: '1d',
                notes: 'Review supporting documents. Provide written advice where required.',
                status: 'draft',
                coordinates: { x: 300, y: 200 },
                sequence: 2,
            },
            {
                title: 'File Application (VCAT)',
                description: 'Prepare and lodge VCAT application with all required documents',
                timeEstimate: '1d',
                notes: 'Confirm correct form and filing fee. Retain lodgement confirmation.',
                status: 'draft',
                coordinates: { x: 500, y: 200 },
                sequence: 3,
            },
            {
                title: 'Directions Hearing',
                description: 'Attend VCAT directions hearing and receive procedural orders',
                timeEstimate: '4h',
                notes: 'Prepare summary of issues. Note all VCAT orders and deadlines.',
                status: 'draft',
                coordinates: { x: 700, y: 200 },
                sequence: 4,
            },
            {
                title: 'Compulsory Conference',
                description: 'Participate in VCAT-facilitated compulsory conference to explore settlement',
                timeEstimate: '3h',
                notes: 'Prepare settlement brief. Obtain client authority on settlement range.',
                status: 'draft',
                coordinates: { x: 900, y: 200 },
                sequence: 5,
            },
            {
                title: 'Hearing',
                description: 'Present case at final VCAT hearing',
                timeEstimate: '1d',
                notes: 'Prepare witness statements and evidence bundle. File submissions on time.',
                status: 'draft',
                coordinates: { x: 1100, y: 200 },
                sequence: 6,
            },
            {
                title: 'Decision & Enforcement',
                description: 'Receive VCAT decision and take steps to enforce if required',
                timeEstimate: '2d',
                notes: 'Advise client of outcome. Initiate enforcement proceedings if non-compliance.',
                status: 'draft',
                coordinates: { x: 1300, y: 200 },
                sequence: 7,
            },
        ],
    },
    {
        name: 'Construction / Operations Workflow',
        description: 'Full project lifecycle from request through post-delivery review',
        category: 'Construction',
        settings: {
            notifications: { email: true, slack: true, inApp: true },
            automation: { autoAssignTasks: true, dueDateReminders: true, escalateOverdueTasks: true },
        },
        status: 'draft',
        steps: [
            {
                title: 'Project Request',
                description: 'Submit and register the project request with scope and objectives',
                timeEstimate: '1d',
                notes: 'Complete project request form. Assign a project sponsor.',
                status: 'draft',
                coordinates: { x: 100, y: 200 },
                sequence: 1,
            },
            {
                title: 'Planning & Design',
                description: 'Develop detailed project plan, design drawings, and timelines',
                timeEstimate: '10d',
                notes: 'Engage design consultants. Confirm stakeholder requirements.',
                status: 'draft',
                coordinates: { x: 300, y: 200 },
                sequence: 2,
            },
            {
                title: 'Approval & Budget',
                description: 'Obtain regulatory approvals and sign off on project budget',
                timeEstimate: '5d',
                notes: 'Submit DA if required. Include contingency in budget estimate.',
                status: 'draft',
                coordinates: { x: 500, y: 200 },
                sequence: 3,
            },
            {
                title: 'Execution (Build Phase)',
                description: 'Carry out construction and operational works on site',
                timeEstimate: '30d',
                notes: 'Hold weekly site meetings. Track progress against programme.',
                status: 'draft',
                coordinates: { x: 700, y: 200 },
                sequence: 4,
            },
            {
                title: 'Quality & Safety Checks',
                description: 'Conduct quality inspections and safety audits throughout build',
                timeEstimate: '5d',
                notes: 'Use inspection checklists. Document and close out all NCRs.',
                status: 'draft',
                coordinates: { x: 900, y: 200 },
                sequence: 5,
            },
            {
                title: 'Project Delivery',
                description: 'Complete practical completion, handover, and client sign-off',
                timeEstimate: '2d',
                notes: 'Issue PC certificate. Handover O&M manuals and as-built drawings.',
                status: 'draft',
                coordinates: { x: 1100, y: 200 },
                sequence: 6,
            },
            {
                title: 'Post-Project Review',
                description: 'Review project outcomes, budget performance, and lessons learned',
                timeEstimate: '2d',
                notes: 'Hold retrospective with project team. Update templates and standards.',
                status: 'draft',
                coordinates: { x: 1300, y: 200 },
                sequence: 7,
            },
        ],
    },
];

module.exports = DEFAULT_TEMPLATES;
